version: "3.7"

services:
  mysql:
    image: mariadb:10.5.8
    restart: always
    hostname: 'mysql'
    environment:
      MYSQL_DATABASE: 'chatbot'
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'secret'
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    depends_on:
      - mysql
    hostname: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5672"]
        interval: 30s
        timeout: 10s
        retries: 5

  app:
    image: chat
    depends_on:
      - mysql
      - rabbitmq
    build:
      context: chat
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DB: 'chatbot'
    env_file: .env

  bot:
    image: bot
    depends_on:
      - mysql
      - rabbitmq
    build:
      context: chatbot
    env_file: .env  

volumes:
  todo-mysql-data: