# syntax=docker/dockerfile:1

FROM golang:1.16-alpine
WORKDIR /chat

COPY go.mod ./
# COPY go.sum ./

RUN go mod download

ADD . ./

RUN go build -o /challenge-chat

EXPOSE 8080

CMD [ "/challenge-chat" ]
