# syntax=docker/dockerfile:1

FROM golang:1.16-alpine
WORKDIR /chatbot

COPY go.mod ./
COPY go.sum ./

RUN go mod download

ADD . ./

RUN go build -o /challenge-chat-bot

CMD [ "/challenge-chat-bot" ]
